### ISSUE TITLE
Possible OneDrive API change

### ISSUE THREAD

**Issue by eugenesmkn** [wooti/onedrive-java-client#12]
Hi!
I try to start syncronize (from Readme) and got the error:
```java
Exception in thread "main" com.google.api.client.http.HttpResponseException: 400 Bad Request
{"error":"invalid_request","error_description":"The provided request must be sent using the HTTP 'POST' method."}
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1061)
	at com.wouterbreukink.onedrive.client.authoriser.OneDriveAuthorisationProvider.getTokenFromCode(OneDriveAuthorisationProvider.java:133)
	at com.wouterbreukink.onedrive.client.authoriser.OneDriveAuthorisationProvider.<init>(OneDriveAuthorisationProvider.java:64)
	at com.wouterbreukink.onedrive.client.authoriser.AuthorisationProvider$FACTORY.create(AuthorisationProvider.java:14)
	at com.wouterbreukink.onedrive.Main.main(Main.java:89)
```

My key file is Ok:
https://login.live.com/oauth20_desktop.srf?code=MY_CODE&lc=1049
I'm sure that I generate it properly (I register this app in https://apps.dev.microsoft.com)
Then I create client id and client secret and after that I generate key file.

Could you show me, please, what I doing wrong?

**Comment by TonyTsangHK** [comment]
Here's the patch for OneDriveAuthorisationProvider.java
You may have a look

``` patch
From 29ab0cc944fceed5ac31a901c61b94570f28a5ac Mon Sep 17 00:00:00 2001
From: Tony Tsang <klsstsang@yahoo.com>
Date: Tue, 15 Nov 2016 11:14:11 +0800
Subject: [PATCH] Fix #12

---
 .../authoriser/OneDriveAuthorisationProvider.java  | 48 +++++++++++-----------
 1 file changed, 24 insertions(+), 24 deletions(-)

diff --git a/src/main/java/com/wouterbreukink/onedrive/client/authoriser/OneDriveAuthorisationProvider.java b/src/main/java/com/wouterbreukink/onedrive/client/authoriser/OneDriveAuthorisationProvider.java
index c3cda36..bfd3d63 100644
--- a/src/main/java/com/wouterbreukink/onedrive/client/authoriser/OneDriveAuthorisationProvider.java
+++ b/src/main/java/com/wouterbreukink/onedrive/client/authoriser/OneDriveAuthorisationProvider.java
@@ -4,6 +4,7 @@ import com.google.api.client.http.GenericUrl;
 import com.google.api.client.http.HttpRequest;
 import com.google.api.client.http.HttpResponse;
 import com.google.api.client.http.HttpTransport;
+import com.google.api.client.http.UrlEncodedContent;
 import com.google.api.client.http.apache.ApacheHttpTransport;
 import com.google.api.client.json.JsonFactory;
 import com.google.api.client.json.JsonObjectParser;
@@ -112,19 +113,19 @@ class OneDriveAuthorisationProvider implements AuthorisationProvider {
     private void getTokenFromCode(final String code) throws IOException {

         log.debug("Fetching authorisation token using authorisation code");
+       
+       Map<String, Object> params = new HashMap<>();
+       
+       params.put("client_id", clientId);
+       params.put("code", code);
+       params.put("grant_type", "authorization_code");
+       params.put("redirect_uri", "https://login.live.com/oauth20_desktop.srf");
+       
         HttpRequest request =
-                HTTP_TRANSPORT.createRequestFactory().buildGetRequest(new GenericUrl("https://login.live.com/oauth20_token.srf") {
-                    @Key("client_id")
-                    private String id = clientId;
-                    @Key("client_secret")
-                    private String secret = clientSecret;
-                    @Key("code")
-                    private String authCode = code;
-                    @Key("grant_type")
-                    private String grantType = "authorization_code";
-                    @Key("redirect_uri")
-                    private String redirect = "https://login.live.com/oauth20_desktop.srf";
-                });
+                HTTP_TRANSPORT.createRequestFactory().buildPostRequest(
+                   new GenericUrl("https://login.live.com/oauth20_token.srf"),
+                   new UrlEncodedContent(params)
+               );

         request.setParser(new JsonObjectParser(JSON_FACTORY));

@@ -134,20 +135,19 @@ class OneDriveAuthorisationProvider implements AuthorisationProvider {
     private void getTokenFromRefreshToken(final String refreshToken) throws IOException {

         log.debug("Fetching authorisation token using refresh token");
+       
+       Map<String, Object> params = new HashMap<>();
+       
+       params.put("client_id", clientId);
+       params.put("refresh_token", refreshToken);
+       params.put("grant_type", "refresh_token");
+       params.put("redirect_uri", "https://login.live.com/oauth20_desktop.srf");

         HttpRequest request =
-                HTTP_TRANSPORT.createRequestFactory().buildGetRequest(new GenericUrl("https://login.live.com/oauth20_token.srf") {
-                    @Key("client_id")
-                    private String id = clientId;
-                    @Key("client_secret")
-                    private String secret = clientSecret;
-                    @Key("refresh_token")
-                    private String token = refreshToken;
-                    @Key("grant_type")
-                    private String grantType = "refresh_token";
-                    @Key("redirect_uri")
-                    private String redirect = "https://login.live.com/oauth20_desktop.srf";
-                });
+                HTTP_TRANSPORT.createRequestFactory().buildPostRequest(
+                   new GenericUrl("https://login.live.com/oauth20_token.srf"),
+                   new UrlEncodedContent(params)
+               );

         request.setParser(new JsonObjectParser(JSON_FACTORY));

-- 
2.6.2.windows.1

```
