### ISSUE TITLE
Error after connection

### ISSUE THREAD

**Issue by lukasamd** [wooti/onedrive-java-client#2]
Hello,
I tried to use this script - first authorize (ok), now sync UP. Effect is error:

```
Exception in thread "main" com.google.api.client.http.HttpResponseException: 400 Bad Request
{"error":"invalid_request","error_description":"The provided request must include a 'code' input parameter."}
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1061)
        at com.wouterbreukink.onedrive.client.authoriser.OneDriveAuthorisationProvider.getTokenFromCode(OneDriveAuthorisationProvider.java:131)
        at com.wouterbreukink.onedrive.client.authoriser.OneDriveAuthorisationProvider.<init>(OneDriveAuthorisationProvider.java:62)
        at com.wouterbreukink.onedrive.client.authoriser.AuthorisationProvider$FACTORY.create(AuthorisationProvider.java:14)
        at com.wouterbreukink.onedrive.Main.main(Main.java:89)
```

My keyfile content:

```
https://login.live.com/oauth20_desktop.srf?code=MY_CODE&lc=1045
```

**Comment by LiohMoeller** [comment]
Could you please create a new release package that contains the fix?

**Comment by wooti** [comment]
Added release 0.2 with the fix in it.
