### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by AndreasTheDead** [wooti/onedrive-java-client#8]
When i want to start onedrive-java i get this output:
_andreas@AndreasUbuntu:~/Downloads$ java -jar onedrive-java-client.jar --direction down --local . --remote ~Desktop/Onedrive/
2015-11-26 19:58:39,695 INFO : Fetched new authorisation token and refresh token for user 8e57677df36b9b2a6914a1d80f014d36
2015-11-26 19:58:40,603 INFO : Using drive with id '2a2ab47b0e1e7d86' (personal). Usage 137.8 GB of 1 TB (13.07%)
Exception in thread "main" com.google.api.client.http.HttpResponseException: 404 Not Found
{"error":{"code":"itemNotFound","message":"Item does not exist"}}
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1061)
    at com.wouterbreukink.onedrive.client.ROOneDriveProvider.getPath(ROOneDriveProvider.java:92)
    at com.wouterbreukink.onedrive.Main.main(Main.java:124)_
How can i fix that?

**Comment by wooti** [comment]
Is it possible that the ~Desktop/Onedrive/ folder does not exist on your remote OneDrive account?

**Comment by AndreasTheDead** [comment]
A thanks i miss understand this option, now it works. But now i become this error at 25-40% of my bigger files
http://pastebin.com/MjQYYHk3
I start the client with the command: _java -jar onedrive-java-client.jar --direction Down --local ./Filme/ --remote Filme/ -r --split-after 5 --hash-compare_

and i will find it rreally nice if you can integrete a Progress bar for bigger files.

**Comment by wooti** [comment]
I've added a ResumableDownloader which should alleviate this problem.
It reports download progress every 5MB (or whatever is specified in --split-after)
